<?php

namespace Bramato\LaravelAi\DTOs;

use WendellAdriel\ValidatedDTO\Casting\ArrayCast;
use WendellAdriel\ValidatedDTO\Casting\BooleanCast;
use WendellAdriel\ValidatedDTO\SimpleDTO;

/**
 * Data Transfer Object for Chat API Responses.
 *
 * Encapsulates the data received from an LLM provider after a chat request.
 * It normalizes common fields while providing access to the raw API response.
 *
 * Note on Instantiation:
 * This DTO is typically instantiated within client implementations using:
 * `new ChatResponse($content, finishReason: $..., model: $..., ...)`
 * The first argument (`content`) is positional, while others commonly use named arguments for clarity.
 */
class ChatResponse extends SimpleDTO
{
    /**
     * The main text content generated by the LLM.
     * If JSON mode was requested and successful, this will contain the raw JSON string.
     * @var string
     */
    public string $content;

    /**
     * The reason the model stopped generating tokens (e.g., 'stop', 'length', 'tool_calls', 'error', 'unknown').
     * @var string
     */
    public string $finishReason;

    /**
     * The specific model identifier that generated this response (e.g., 'gpt-4-turbo', 'gemini-1.5-pro-latest').
     * @var string
     */
    public string $model;

    /**
     * A unique identifier for the chat interaction or message, as provided by the API.
     * Format varies significantly between providers.
     * @var string
     */
    public string $id;

    /**
     * Token usage statistics for the request, if provided by the API.
     * Typically includes ['prompt_tokens' => int, 'completion_tokens' => int, 'total_tokens' => int].
     * Structure may vary slightly by provider.
     * @var array|null
     */
    public ?array $usage;

    /**
     * Indicates if JSON mode was requested AND the `content` was successfully parsed as JSON.
     * Set to `true` only if both conditions are met.
     * @var bool
     */
    public bool $isJson;

    /**
     * If `isJson` is true, this property holds the decoded content (typically an associative array or object).
     * If `isJson` is false or decoding failed, this will be `null`.
     * @var mixed|null
     */
    public mixed $decodedJsonContent;

    /**
     * The original, unprocessed response array received directly from the provider's API.
     * Useful for debugging or accessing provider-specific data not mapped to other properties.
     * @var array|null
     */
    public ?array $rawResponse;

    /**
     * Defines the default values for the DTO properties.
     *
     * @return array<string, mixed> Default values.
     */
    protected function defaults(): array
    {
        return [
            'usage' => null,
            'isJson' => false,
            'decodedJsonContent' => null,
            'rawResponse' => null,
        ];
    }

    /**
     * Defines the type casting for the DTO properties.
     *
     * @return array<string, object> Type casts.
     */
    protected function casts(): array
    {
        return [
            // Use ArrayCast to ensure these are always arrays or null/empty array if input is invalid/null
            'usage' => new ArrayCast(),
            'isJson' => new BooleanCast(),
            'rawResponse' => new ArrayCast(),
            // decodedJsonContent is mixed and set manually in clients, no cast needed here.
        ];
    }
}
