<?php

namespace Bramato\LaravelAi\DTOs;

use WendellAdriel\ValidatedDTO\Casting\ArrayCast;
use WendellAdriel\ValidatedDTO\Casting\FloatCast;
use WendellAdriel\ValidatedDTO\SimpleDTO;

/**
 * Data Transfer Object for the response of the ImageDescriptionService.
 */
class ImageDescriptionResponseDto extends SimpleDTO
{
    /**
     * The textual description of the image generated by the AI.
     * Might contain a fallback message if description failed.
     */
    public string $description;

    /**
     * Optional confidence score for the description (if provided by the API).
     */
    public ?float $confidence;

    /**
     * Optional array of tags or keywords related to the image (if provided by the API).
     *
     * @var array<int, string>
     */
    public array $tags;

    /**
     * Defines the default values for the properties of the DTO.
     *
     * @return array<string, mixed>
     */
    protected function defaults(): array
    {
        return [
            'description' => 'Image description not available.', // Default fallback
            'confidence' => null,
            'tags' => [],
        ];
    }

    /**
     * Defines the type casting for the properties of the DTO.
     *
     * @return array<string, object>
     */
    protected function casts(): array
    {
        return [
            'confidence' => new FloatCast, // Cast to float if present
            'tags' => new ArrayCast,
        ];
    }
}
